AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  music-cards-lambda

  Sample SAM Template for music-cards-lambda

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 300

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: music_cards_service/
      Handler: app.lambda_handler
      Runtime: python3.8
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /hello
            Method: get

  GetFrontFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    DependsOn:
      - CacheBucket
    Properties:
      CodeUri: music_cards_service/
      Handler: app.get_front
      Runtime: python3.8
      Environment:
        Variables:
          CACHE_BUCKET:
            Ref: "CacheBucket"
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /front
            Method: get

  GetBackFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    DependsOn:
      - CacheBucket
    Properties:
      CodeUri: music_cards_service/
      Handler: app.get_back
      Runtime: python3.8
      Environment:
        Variables:
          CACHE_BUCKET:
            Ref: "CacheBucket"
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /back
            Method: get

  CacheBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: "music-cards-cache"

  MyBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      PolicyDocument:
        Id: BucketPolicy
        Version: 2012-10-17
        Statement:
          - Sid: AccessAll
            Action: s3:*
            Effect: Allow
            # Beware: this makes your bucket public!
            Principal: "*"
            Resource: !Join
              - ''
              - - 'arn:aws:s3:::'
                - !Ref CacheBucket
                - /*
      Bucket: !Ref CacheBucket

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn
  GetFrontApi:
    Description: "API Gateway endpoint URL for Prod stage for Get Front function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/front/"
  GetFrontFunction:
    Description: "Get Front Lambda Function ARN"
    Value: !GetAtt GetFrontFunction.Arn
  GetFrontFunctionIamRole:
    Description: "Implicit IAM Role created for Get Front function"
    Value: !GetAtt GetFrontFunctionRole.Arn
  GetBackApi:
    Description: "API Gateway endpoint URL for Prod stage for Get Back function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/back/"
  GetBackFunction:
    Description: "Get Back Lambda Function ARN"
    Value: !GetAtt GetBackFunction.Arn
  GetBackFunctionIamRole:
    Description: "Implicit IAM Role created for Get Back function"
    Value: !GetAtt GetBackFunctionRole.Arn
